/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prj.tst.sandbox2;

public class MyFirstProgram {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new MyFirstProgram().getGreeting());
        hello("me");
        Square s =new Square(9);
       // s.l=6;
        double len=5;
        System.out.println(s.area());
        Rectangle r=new Rectangle(10,11);
        //r.a=4;
        //r.b=5;
        double a=2;
        double b=3;
        System.out.println(r.area());

        Point p1 = new Point(1,1);
        Point p2=new Point(3,3);
        System.out.println(distance(p1,p2));
        System.out.println(p1.distance(p2));
    }

    public static void hello(String somebody) {
        System.out.println("Hello "+somebody);
    }

    //public static double area (Rectangle r){
    //    return r.a*r.b;
   // }

    public static double distance(Point p1, Point p2){
        return Math.sqrt((p2.x- p1.x)*(p2.x- p1.x)+(p2.y- p1.y)*(p2.y- p1.y));
    }
}
