/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prj.tst.sandbox2;

public class MyFirstProgram {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new MyFirstProgram().getGreeting());
        hello("me");
        double len=5;
        double a=2;
        double b=3;
        System.out.println(area(len));
        System.out.println(area(a, b));
    }

    public static void hello(String somebody) {
        System.out.println("Hello "+somebody);
    }
    public static double area(double l){
        return l*l;
    }
    public static double area (double a, double b){
        return a*b;
    }
}
